apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 30080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx
