apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: nginx-cm
              mountPath: /etc/nginx
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-cm
          configMap:
            name: nginx-cm
        - name: nginx-volume
          hostPath:
            path: /var/nginxserver
