apiVersion: v1
kind: Secret
metadata:
  name: nginx-https-secret
type: Opaque
stringData:
  example.com.crt: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  example.com.key: |
    -----BEGIN RSA PRIVATE KEY-----
    ...
    -----END RSA PRIVATE KEY-----
