apiVersion: v1
kind: Service
metadata:
  name: nginx-https-svc
  labels:
    app: nginx-https
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 31080
      targetPort: 80
      protocol: TCP
    - name: https
      port: 31443
      targetPort: 443
      protocol: TCP
  selector:
    app: nginx-https
