apiVersion: v1
kind: Service
metadata:
  name: nginx-http-svc
  labels:
    app: nginx-http
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 30080
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-http
