version: '3'

services:
  app:
    image: nginx:alpine
    container_name: nginx-file-server
    ports:
      - 80:80
    volumes:
      - /etc/nginx-file-server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${SHARE_DIR}:/share
    restart: unless-stopped
