version: '3.8'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
     - '8081:8081'
    volumes:
      - nexus_data:/nexus-data
    environment:
      - 'REGISTRY_HTTP_RELATIVEURLS=true'
    restart: unless-stopped

volumes:
  nexus_data: