version: '3.8'

services:
  cloudflared:
    image: 'cloudflare/cloudflared:latest'
    container_name: cloudflared
    network_mode: bridge
    command: tunnel --no-autoupdate run --token ${TOKEN} # replace UUID with your tunnel UUID
    restart: unless-stopped
